apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: three-tier
spec: 
  selector:
    tier: backend
  ports:
    - port: 3500
      name: backend-svc
      targetPort: 3500
      protocol: TCP
  type: ClusterIP
