apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend-deploy
  namespace: three-tier
  labels: 
    tier: backend 
spec: 
  replicas: 2
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector: 
    matchLabels:
      tier: backend 
  template:
    metadata:
      namespace: three-tier
      name: backend-pod
      labels:
        tier: backend 
    spec:
      containers:
      - name: backend-container
        image: 992382401555.dkr.ecr.us-east-1.amazonaws.com/three-tier-backend:latest
        imagePullPolicy: Always
        env:
          - name: MONGO_CONN_STR
            value: mongodb://mongo-svc/todo?directConnection=true
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: db_username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: db_password
        ports:
          - containerPort: 3500
        resources:
          requests:
            memory: "4Gi"  
            cpu: "1000m"      
          limits:
            memory: "4Gi"
            cpu: "1000m"
                      
        livenessProbe:
          httpGet:
            path: /ok
            port: 3500
          initialDelaySeconds: 2
          periodSeconds: 5
        
        readinessProbe:
          httpGet:
            path: /ok
            port: 3500
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
