apiVersion: v1 
kind: Service
metadata:
  name: frontend-svc
  namespace: three-tier
spec:
  selector:
    tier: frontend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: frontend-svc
  type: ClusterIP