apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
  name: mongo-pvc
  namespace: three-tier
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: mongo-sc
  resources:
    requests:
      storage: 5Gi
    
