apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-sc
  namespace: three-tier
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"  
provisioner: efs.csi.aws.com
reclaimPolicy: Delete
