apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
  name: mongo-pvc
  namespace: three-tier
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resouces:
    requests:
      storage: 5Gi
    