apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mongo-deploy
  namespace: three-tier
  tier: db 
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: db 
  template:
    metadata:
      namespace: three-tier
      tier: db 
    spec:
      containers:
        - name: mongo-pod
          image: mongo:4.4.6
          command:
            - "numactl"
            - "--interleave=all"
            - "mongod"
            - "--wiredTigerCacheSizeGB"
            - "0.1"
            - "--bind_ip" 
            - "0.0.0.0"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limit:
              memory: "1Gi"
              cpu: "500m"
          env: 
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: db_username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: db_password
          ports:
            - containerPort: 27017
          
          
          volumeMount:
            - name: mongo-vol
              mountpath: /data/mongodb
      volumes:         
        - name: mongo-vol
          persistentVolumeClaim:
            claimName: mongo-pvc