apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: mongo-pv 
  namespace: three-tier
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/mongodb