apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: mongo-pv 
  namespace: three-tier
spec:
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
  capacity:
    storage: 10Gi
  storageClassName: mongo-sc
  mountOptions:
    - tls 
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07abfaeb219e12826

