apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: mongo-pv 
  namespace: three-tier
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  capacity:
    storage: 10Gi
  storageClassName: mongo-sc
  mountOptions:
    - tls 
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0a14425b88f5d6bd1
