apiVersion: v1 
kind: Service 
metadata:
  name: mongo-svc
  namespace: three-tier
spec:
  selector:
    tier: db
  ports:
    - port: 27017
      targetPort: 27017
      name: mongo-svc
      protocol: TCP
