apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mongo-deploy
  namespace: three-tier
  labels:
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: db 
  template:
    metadata:
      namespace: three-tier
      name: mongo-pod
      labels:
        tier: db
    spec:
      initContainers:
        - name: init-efs-mount
          image: amazonlinux
          command:
            [
              "/bin/sh",
              "-c",
              "mkdir -p /mnt/efs && mount -t nfs4 -o nfsvers=4.1 fs-0d2d9f07d86662213.efs.<region>.amazonaws.com:/ /mnt/efs && mkdir -p /mnt/efs/mongo && chmod 777 /mnt/efs/mongo",
            ]
          volumeMounts:
            - name: efs-volume
              mountPath: /mnt/efs    
      containers:
        - name: mongo-container
          image: mongo:4.4.6
          command:
            - "numactl"
            - "--interleave=all"
            - "mongod"
            - "--wiredTigerCacheSizeGB"
            - "0.1"
            - "--bind_ip" 
            - "0.0.0.0"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env: 
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: db_username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: db_password
          ports:
            - containerPort: 27017
          
          
          volumeMounts:
            - name: mongo-vol
              mountPath: /data/mongodb
      volumes:         
        - name: mongo-vol
          persistentVolumeClaim:
            claimName: mongo-pvc
