apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-sc
  namespace: three-tier
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"  
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0fca4442da91173c3::fsap-02ab867780ac51861
reclaimPolicy: Delete
